apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-gateway-worker
  namespace: sms-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-gateway-worker
  template:
    metadata:
      labels:
        app: sms-gateway-worker
    spec:
      containers:
        - name: worker
          image: mudassarm30/sms-gateway-worker:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "app.jar", "-mock", "Ufone,Telenor"]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/smsgatewaydb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
